<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\uploads\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Discord.Application\Discord.Application.csproj" />
	  <ProjectReference Include="..\Discord.Core\Discord.Core.csproj" />
	  <ProjectReference Include="..\Discord.Infrastructure\Discord.Infrastructure.csproj" />
	</ItemGroup>

</Project>